### ISSUE TITLE
One compilation bug for flowlets.sk

### ISSUE THREAD

**Issue by XiangyuG** [chipmunk-project/chipmunk#117]
**flowlets.sk file content:**
```
| StateAndPacket | program(| StateAndPacket | state_and_packet) {
  state_and_packet.pkt_0 = state_and_packet.pkt_0;
  state_and_packet.pkt_1 = state_and_packet.pkt_1;
  if (state_and_packet.pkt_2 - state_and_packet.state_group_1_state_0 > 5) {
    state_and_packet.state_group_0_state_0 = state_and_packet.pkt_0;

    ;
  }
  state_and_packet.state_group_1_state_0 = state_and_packet.pkt_2;
  state_and_packet.pkt_3 = state_and_packet.state_group_0_state_0;
  return state_and_packet;
}
```

When you compile above flowlets.sk, we get an error. 

`time iterative_solver /tmp/chipmunk_program/flowlets.sk example_alus/pred_raw.stateful_alu chipc/templates/stateless_alu.j2 5 4 10`

**Error output:**
SKETCH version 1.7.5
Benchmark = flowlets_pred_raw_stateless_alu_5_4_codegen_iteration_2.sk
    [1557874385.5220 - ERROR] [SKETCH] Error at node: The struct does not have a field named state_group_0_state_0_a_a_0 (at flowlet..tion_2.sk:4081)
    [1557874385.5250 - ERROR] [SKETCH] Error at node: The struct does not have a field named state_group_0_state_0_a_a_0 (at flowlet..tion_2.sk:4090)
    [1557874385.5251 - ERROR] [SKETCH] Error at node: The struct does not have a field named state_group_0_state_0_a_a_0 (at flowlet..tion_2.sk:4099)
    [1557874385.5252 - ERROR] [SKETCH] Error at node: The struct does not have a field named state_group_0_state_0_a_a_0 (at flowlet..tion_2.sk:4108)
    [1557874385.5260 - ERROR] [SKETCH] Error at node: The struct does not have a field named state_group_0_state_0_a_a_0 (at flowlet..tion_2.sk:4117)
    [1557874385.5261 - ERROR] [SKETCH] Error at node: The struct does not have a field named state_group_0_state_0_a_a_0 (at flowlet..tion_2.sk:4126)
    [1557874385.5262 - ERROR] [SKETCH] Error at node: The struct does not have a field named state_group_0_state_0_a_a_0 (at flowlet..tion_2.sk:4135)
    [1557874385.5700 - ERROR] [SKETCH] Program Parse Error: Semantic check failed
    [1557874385.5710 - DEBUG] [SKETCH] stack trace written to file: /home/xiangyug/.sketch/tmp/stacktrace.txt

**Comment by taegyunkim** [comment]
Do you know at which step does this generate error?
It looks like we're adding a variable or a field that is not properly named.

**Comment by taegyunkim** [comment]
```
Sketch file is  flowlets_pred_raw_stateless_alu_5_4_codegen_iteration_2.sk
Traceback (most recent call last):
  File "/home/taegyunk/.pyenv/versions/chipmunk/bin/iterative_solver", line 11, in <module>
    load_entry_point('chipc', 'console_scripts', 'iterative_solver')()
  File "/home/taegyunk/Workspace/chipmunk/chipc/iterative_solver.py", line 201, in run_main
    sys.exit(main(sys.argv))
  File "/home/taegyunk/Workspace/chipmunk/chipc/iterative_solver.py", line 167, in main
    if args.parallel == 'serial_codegen' else \
  File "/home/taegyunk/Workspace/chipmunk/chipc/compiler.py", line 130, in serial_codegen
    str(iter_cnt) + '.sk'))
  File "/home/taegyunk/Workspace/chipmunk/chipc/compiler.py", line 111, in single_codegen_run
    slv_parallel=slv_parallel)
  File "/home/taegyunk/Workspace/chipmunk/chipc/sketch_utils.py", line 20, in synthesize
    check_syntax(sketch_file_name)
  File "/home/taegyunk/Workspace/chipmunk/chipc/sketch_utils.py", line 15, in check_syntax
    'Output pasted below:\n\n' + output)
Exception: flowlets_pred_raw_stateless_alu_5_4_codegen_iteration_2.sk contains a syntax error.Output pasted below:
SKETCH version 1.7.5
Benchmark = flowlets_pred_raw_stateless_alu_5_4_codegen_iteration_2.sk
    [1557897406.2890 - ERROR] [SKETCH] Error at node: The struct does not have a field named state_group_1_state_0_b_b_0 (at flowlet..tion_2.sk:4081)
    [1557897406.2920 - ERROR] [SKETCH] Error at node: The struct does not have a field named state_group_1_state_0_b_b_0 (at flowlet..tion_2.sk:4090)
    [1557897406.2921 - ERROR] [SKETCH] Error at node: The struct does not have a field named state_group_1_state_0_b_b_0 (at flowlet..tion_2.sk:4099)
    [1557897406.2922 - ERROR] [SKETCH] Error at node: The struct does not have a field named state_group_1_state_0_b_b_0 (at flowlet..tion_2.sk:4108)
    [1557897406.2930 - ERROR] [SKETCH] Error at node: The struct does not have a field named state_group_1_state_0_b_b_0 (at flowlet..tion_2.sk:4117)
    [1557897406.2931 - ERROR] [SKETCH] Error at node: The struct does not have a field named state_group_1_state_0_b_b_0 (at flowlet..tion_2.sk:4126)
    [1557897406.2932 - ERROR] [SKETCH] Error at node: The struct does not have a field named state_group_1_state_0_b_b_0 (at flowlet..tion_2.sk:4135)
    [1557897406.3320 - ERROR] [SKETCH] Program Parse Error: Semantic check failed
    [1557897406.3330 - DEBUG] [SKETCH] stack trace written to file: /home/taegyunk/.sketch/tmp/stacktrace.txt
```

**Comment by anirudhSK** [comment]
@taegyunkim: How does #120 fix this bug?

**Comment by taegyunkim** [comment]
This bug is caused by [this code](https://github.com/chipmunk-project/chipmunk/pull/120/files#diff-5d5ae09607e47af7e78753bb535772c6L67). 

```Python
        # The variable names used by sketch have trailing _\d+_\d+_\d+ pattern,
        # need to remove them to get original variable names.
        var_name = re.sub(r'_\d+_\d+_\d+$', '', var.name(), count=1)
```

I have assumed that sketch modifies the variable names with trailing _\d+_\d+_\d+. As it turned out, that was not the case. #120 updated the code to explicitly capture packet and state variable names.

**Comment by anirudhSK** [comment]
OK. Can we double check that it actually fixes 117 before we merge?

**Comment by taegyunkim** [comment]
Sure, I've been running the command since I created the pull request (about 7 hours). I will update the thread once the command returns something or passes the point where it failed.

**Comment by taegyunkim** [comment]
```
taegyunk@cyclops ~/W/chipmunk ❯❯❯ iterative_solver /tmp/chipmunk_program/flowlets.sk example_alus/pred_raw.stateful_alu chipc/templates/stateless_alu.j2 5 4 10
Total number of hole bits is 470
Sketch file is  flowlets_pred_raw_stateless_alu_5_4_codegen_iteration_1.sk

Iteration #1
Synthesis succeeded with 2 bits, proceeding to verification.
Verification failed. Trying again.
Generating counterexamples of 2 bits.
Failed to generate counterexamples, z3 returned unsat
Setting value 0 for pkt_0
Setting value 0 for pkt_1
Setting value 0 for pkt_2
Setting value 0 for pkt_3
Setting value 0 for state_group_1_state_0
Setting value 0 for state_group_0_state_0
Generating counterexamples of 3 bits.
Generating counterexamples of 4 bits.
Generating counterexamples of 5 bits.
Generating counterexamples of 6 bits.
Generating counterexamples of 7 bits.
Generating counterexamples of 8 bits.
Generating counterexamples of 9 bits.
Total number of hole bits is 470
Sketch file is  flowlets_pred_raw_stateless_alu_5_4_codegen_iteration_2.sk
Iteration #2
FAILURE: Failed synthesis at 2 bits.
```

[sketch output](https://gist.github.com/taegyunkim/19d2c7d02fbe82db123eafab228170b7)
```
----- Statistics -----
Total elapsed time (ms):  4.4499e+07
Model building time (ms): 0.044
Solution time (ms):       0
Max virtual mem (bytes):  3881164800
Max resident mem (bytes): 3740319744
Max private mem (bytes):  3876368384
cegis: core/Solver.cpp:577: void MSsolverNS::Solver::analyze(MSsolverNS::Clause*, MSsolverNS::vec<MSsolverNS::Lit>&, int&): Assertion `confl != NULL' failed.
Someone threw a C-style assertion.
[SATBackend] Stats for last run:
      [solution stats]
      successful? ---------------------> false
      elapsed time (s) ----------------> 44499.336
      model building time (s) ---------> -0.001
      solution time (s) ---------------> -0.001
      max memory usage (MiB) ----------> -9.536743E-7
      [SAT-specific solution stats]
      initial number of nodes ---------> -1
      number of nodes after opts ------> -1
      number of controls --------------> -1
      total number of control bits ----> -1

[SATBackend] Solver exit value: 3
[SATBackend] The sketch cannot be resolved.
    [0;31m[1557993462.0170 - ERROR] [SKETCH] Sketch Not Resolved Error: cegis: core/Solver.cpp:577: void MSsolverNS::Solver::analyze(MSsolverNS::Clause*, MSsolverNS::vec<MSsolverNS::Lit>&, int&): Assertion `confl != NULL' failed.
Someone threw a C-style assertion.
The sketch could not be resolved.[0m
    [0;32m[1557993462.0180 - DEBUG] [SKETCH] stack trace written to file: /home/taegyunk/.sketch/tmp/stacktrace.txt[0m
    [0;32m[1557993462.0190 - DEBUG] Backend solver input file at /home/taegyunk/.sketch/tmp/flowlets_pred_raw_stateless_alu_5_4_codegen_iteration_2.sk/input0.tmp[0m
Total time = 44500373
Command exited with non-zero status 1
44286.29user 241.68system 12:21:40elapsed 100%CPU (0avgtext+0avgdata 3652724maxresident)k
0inputs+24608outputs (0major+309595754minor)pagefaults 0swaps

```

**Comment by anirudhSK** [comment]
OK. This seems like a new issue. Let's merge the previous change and investigate this issue separately.
