### ISSUE TITLE
AssertionError when run iterative_solver example_specs/simple.sk example_alus/stateful_alus/raw.alu example_alus/stateless_alus/stateless_alu.alu 2 2 "0,1,2,3" 10 --hole-elimination

### ISSUE THREAD

**Issue by SOANykun** [chipmunk-project/chipmunk#203]
Iteration #1
Traceback (most recent call last):
  File "/home/colosseum/chipmunk/chipc/iterative_solver.py", line 326, in <module>
    run_main()
  File "/home/colosseum/chipmunk/chipc/iterative_solver.py", line 322, in run_main
    sys.exit(main(sys.argv))
  File "/home/colosseum/chipmunk/chipc/iterative_solver.py", line 267, in main
    additional_testcases=additional_testcases)
  File "/home/colosseum/chipmunk/chipc/compiler.py", line 180, in serial_codegen
    str(iter_cnt) + '.sk'))
  File "/home/colosseum/chipmunk/chipc/compiler.py", line 146, in single_codegen_run
    additional_testcases=additional_testcases)
  File "/home/colosseum/chipmunk/chipc/sketch_code_generator.py", line 334, in generate_sketch
    self.generate_stateful_operand_muxes())
  File "/home/colosseum/chipmunk/chipc/sketch_code_generator.py", line 251, in generate_stateful_operand_muxes
    assert (self.num_operands_to_stateful_alu_ > 0)
AssertionError

Process finished with exit code 1

**Comment by XiangyuG** [comment]
Hi,

It does not happen over my machine. BTW, we have already moved everything to https://github.com/chipmunk-project/chipmunk-tofino repo. Can you switch to that one and try same command again?

Xiangyu
