### ISSUE TITLE
Proper use of relative file path

### ISSUE THREAD

**Issue by taegyunkim** [chipmunk-project/chipmunk#48]
Most of the functions assume that the scripts are run from the directory they are in.
And this does not work. 

```Shell
$> pwd 
/Users/taegyunkim/Workspace/chipmunk
$> cd ..
$> pwd
/Users/taegyunkim/Workspace
$> python3 chipmunk/chipmunk.py chipmunk/example_specs/simple.sk chipmunk/example_alus/raw.stateful_alu 2 2 codegen simple serial
Traceback (most recent call last):
  File "chipmunk/chipmunk.py", line 57, in <module>
    main(sys.argv)
  File "chipmunk/chipmunk.py", line 29, in main
    num_alus_per_stage, sketch_name, parallel_or_serial)
  File "/Users/taegyunkim/Workspace/chipmunk/compiler.py", line 46, in __init__
    self.alu_definitions = self.sketch_generator.generate_alus()
  File "/Users/taegyunkim/Workspace/chipmunk/sketch_generator.py", line 186, in generate_alus
    for k in range(0, self.num_phv_containers_)
  File "/Users/taegyunkim/Workspace/chipmunk/sketch_generator.py", line 67, in generate_stateless_alu
    operand_mux_template = self.jinja2_env_.get_template("mux.j2")
  File "/Users/taegyunkim/.pyenv/versions/3.7.2/lib/python3.7/site-packages/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/taegyunkim/.pyenv/versions/3.7.2/lib/python3.7/site-packages/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/taegyunkim/.pyenv/versions/3.7.2/lib/python3.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/taegyunkim/.pyenv/versions/3.7.2/lib/python3.7/site-packages/jinja2/loaders.py", line 187, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: mux.j2
```

Also, when writing to files, we currently writes to the same directory as the scripts are located. Instead of doing these, write to the directory where the command was invoked.

**Comment by taegyunkim** [comment]
Necessary step for #38
